# Generated by Django 4.2.30 on 2026-05-12 05:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# api.migrations.0006_scenario_step_result_snapshot


def backfill_scenario_names(apps, schema_editor):
    """
    数据迁移：回填 ScenarioStepResult.scenario_name（场景名称快照）。

    背景：
    - 平台的场景步骤结果需要展示“执行当时”的场景名称
    - 但场景名称未来可能会被用户修改
    - 因此在结果表中保存一份快照字段 scenario_name，并在字段引入时进行一次历史数据回填
    """
    ScenarioStepResult = apps.get_model("api", "ScenarioStepResult")
    for result in ScenarioStepResult.objects.select_related("scenario").iterator():
        if result.scenario_id and result.scenario and not result.scenario_name:
            result.scenario_name = result.scenario.name
            result.save(update_fields=["scenario_name"])

class Migration(migrations.Migration):

    replaces = [('api', '0001_initial'), ('api', '0002_dependencies_progress'), ('api', '0003_platform_upgrade'), ('api', '0004_quality_governance'), ('api', '0005_environment_cookie'), ('api', '0006_scenario_step_result_snapshot'), ('api', '0007_scenario_step_result_scenario_name_nullable'), ('api', '0008_task_event'), ('api', '0009_ui_automation'), ('api', '0010_alter_uistep_dependencies'), ('api', '0011_po_ddt')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('base_url', models.URLField(blank=True)),
                ('headers', models.JSONField(blank=True, default=dict)),
                ('verify_ssl', models.BooleanField(default=False)),
                ('timeout_seconds', models.PositiveIntegerField(default=10)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='environments', to='api.project')),
            ],
            options={
                'unique_together': {('project', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='api.project')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
                'unique_together': {('project', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ApiDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('path', models.CharField(max_length=500)),
                ('method', models.CharField(max_length=16)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apis', to='api.module')),
                ('default_headers', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['module_id', 'id'],
                'unique_together': {('module', 'path', 'method')},
            },
        ),
        migrations.CreateModel(
            name='ApiCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case_code', models.CharField(max_length=80)),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=200)),
                ('header', models.JSONField(blank=True, default=dict)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('expect', models.JSONField(blank=True, default=dict)),
                ('level', models.PositiveIntegerField(default=1)),
                ('rely', models.CharField(blank=True, max_length=200)),
                ('is_setup', models.BooleanField(default=False)),
                ('enabled', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('api', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='api.apidefinition')),
                ('extractors', models.JSONField(blank=True, default=list)),
                ('dependencies', models.ManyToManyField(blank=True, to='api.apicase')),
                ('tags', models.JSONField(blank=True, default=list)),
                ('suite', models.CharField(blank=True, max_length=80)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('estimated_duration_ms', models.PositiveIntegerField(default=1000)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
                'unique_together': {('api', 'case_code', 'is_setup')},
            },
        ),
        migrations.CreateModel(
            name='TestPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('levels', models.JSONField(blank=True, default=list)),
                ('cases', models.ManyToManyField(blank=True, to='api.apicase')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='test_plans', to='api.environment')),
                ('modules', models.ManyToManyField(blank=True, to='api.module')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_plans', to='api.project')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='TestTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PENDING', '待执行'), ('RUNNING', '执行中'), ('PASSED', '通过'), ('FAILED', '失败'), ('CANCELED', '已取消')], default='PENDING', max_length=20)),
                ('progress', models.PositiveIntegerField(default=0)),
                ('total_count', models.PositiveIntegerField(default=0)),
                ('passed_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('report_xml_path', models.CharField(blank=True, max_length=500)),
                ('report_html_path', models.CharField(blank=True, max_length=500)),
                ('log', models.TextField(blank=True)),
                ('failure_reason', models.TextField(blank=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='api.testplan')),
                ('current_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='running_tasks', to='api.apicase')),
                ('current_case_code', models.CharField(blank=True, max_length=80)),
                ('current_case_title', models.CharField(blank=True, max_length=200)),
                ('current_step_message', models.CharField(blank=True, max_length=300)),
                ('skipped_count', models.PositiveIntegerField(default=0)),
                ('current_object_type', models.CharField(blank=True, max_length=30)),
                ('current_step_name', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=120)),
                ('value', models.TextField(blank=True)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('enabled', models.BooleanField(default=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variables', to='api.project')),
            ],
            options={
                'ordering': ['key'],
                'unique_together': {('project', 'key')},
            },
        ),
        migrations.CreateModel(
            name='EnvironmentVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=120)),
                ('value', models.TextField(blank=True)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('enabled', models.BooleanField(default=True)),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variables', to='api.environment')),
            ],
            options={
                'ordering': ['key'],
                'unique_together': {('environment', 'key')},
            },
        ),
        migrations.CreateModel(
            name='ScenarioCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('level', models.PositiveIntegerField(default=1)),
                ('enabled', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scenarios', to='api.module')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenarios', to='api.project')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ScenarioStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('header', models.JSONField(blank=True, default=dict)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('expect', models.JSONField(blank=True, default=dict)),
                ('extractors', models.JSONField(blank=True, default=list)),
                ('enabled', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('api', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scenario_steps', to='api.apidefinition')),
                ('dependencies', models.ManyToManyField(blank=True, to='api.scenariostep')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='api.scenariocase')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('mode', models.CharField(choices=[('SIMPLE', '简单周期'), ('CRON', 'Cron')], default='SIMPLE', max_length=20)),
                ('simple_type', models.CharField(choices=[('DAILY', '每天'), ('WEEKLY', '每周'), ('HOURLY', '每 N 小时')], default='DAILY', max_length=20)),
                ('interval_hours', models.PositiveIntegerField(default=1)),
                ('weekdays', models.JSONField(blank=True, default=list)),
                ('run_time', models.TimeField(blank=True, null=True)),
                ('cron', models.CharField(blank=True, max_length=120)),
                ('enabled', models.BooleanField(default=False)),
                ('next_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='api.testplan')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='testplan',
            name='scenarios',
            field=models.ManyToManyField(blank=True, to='api.scenariocase'),
        ),
        migrations.AddField(
            model_name='testplan',
            name='api_definitions',
            field=models.ManyToManyField(blank=True, to='api.apidefinition'),
        ),
        migrations.AddField(
            model_name='testplan',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='testplan',
            name='suites',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case_code', models.CharField(max_length=80)),
                ('title', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('PASSED', '通过'), ('FAILED', '失败'), ('ERROR', '错误'), ('SKIPPED', '跳过')], max_length=20)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('request_data', models.JSONField(blank=True, default=dict)),
                ('response_status', models.IntegerField(blank=True, null=True)),
                ('response_body', models.TextField(blank=True)),
                ('assertion_error', models.TextField(blank=True)),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.apicase')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='api.testtask')),
                ('failure_category', models.CharField(blank=True, max_length=40)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='EnvironmentCookie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('domain', models.CharField(max_length=255)),
                ('path', models.CharField(default='/', max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('value', models.TextField(blank=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('secure', models.BooleanField(default=False)),
                ('http_only', models.BooleanField(default=False)),
                ('enabled', models.BooleanField(default=True)),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cookies', to='api.environment')),
            ],
            options={
                'ordering': ['domain', 'path', 'name'],
                'unique_together': {('environment', 'domain', 'path', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ScenarioStepResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('step_name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('PASSED', '通过'), ('FAILED', '失败'), ('ERROR', '错误'), ('SKIPPED', '跳过')], max_length=20)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('request_data', models.JSONField(blank=True, default=dict)),
                ('response_status', models.IntegerField(blank=True, null=True)),
                ('response_body', models.TextField(blank=True)),
                ('assertion_error', models.TextField(blank=True)),
                ('scenario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.scenariocase')),
                ('step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.scenariostep')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_results', to='api.testtask')),
                ('failure_category', models.CharField(blank=True, max_length=40)),
                ('scenario_name', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.RunPython(
            code=backfill_scenario_names,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='scenariostepresult',
            name='scenario_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='TaskEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('level', models.CharField(choices=[('INFO', '信息'), ('WARN', '警告'), ('ERROR', '错误')], default='INFO', max_length=10)),
                ('category', models.CharField(choices=[('TASK', '任务'), ('REQUEST', '请求'), ('ASSERTION', '断言'), ('EXTRACTOR', '变量提取'), ('DEPENDENCY', '依赖'), ('REPORT', '报告'), ('SYSTEM', '系统')], default='TASK', max_length=20)),
                ('message', models.CharField(blank=True, max_length=300)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('object_type', models.CharField(blank=True, max_length=30)),
                ('case_code', models.CharField(blank=True, max_length=80)),
                ('step_name', models.CharField(blank=True, max_length=200)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='api.testtask')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='UiScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('level', models.PositiveIntegerField(default=1)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('enabled', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ui_scenarios', to='api.module')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ui_scenarios', to='api.project')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='UiStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('GOTO', '打开页面'), ('CLICK', '点击'), ('FILL', '输入'), ('PRESS', '按键'), ('WAIT', '等待'), ('ASSERT', '断言')], default='CLICK', max_length=20)),
                ('target', models.JSONField(blank=True, default=dict)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('assertions', models.JSONField(blank=True, default=dict)),
                ('enabled', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='api.uiscenario')),
                ('dependencies', models.ManyToManyField(blank=True, to='api.uistep')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='UiTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mode', models.CharField(choices=[('HEADLESS', '无头'), ('HEADED', '有头')], default='HEADLESS', max_length=10)),
                ('progress', models.PositiveIntegerField(default=0)),
                ('total_steps', models.PositiveIntegerField(default=0)),
                ('passed_steps', models.PositiveIntegerField(default=0)),
                ('failed_steps', models.PositiveIntegerField(default=0)),
                ('skipped_steps', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('PENDING', '待执行'), ('RUNNING', '执行中'), ('PASSED', '通过'), ('FAILED', '失败'), ('CANCELED', '已取消')], default='PENDING', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True)),
                ('report_dir', models.CharField(blank=True, max_length=500)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='api.uiscenario')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='UiStepResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('step_name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('PASSED', '通过'), ('FAILED', '失败'), ('ERROR', '错误'), ('SKIPPED', '跳过')], max_length=20)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('failure_category', models.CharField(blank=True, max_length=40)),
                ('error_message', models.TextField(blank=True)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.uistep')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='api.uitask')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='UiTaskEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('level', models.CharField(choices=[('INFO', '信息'), ('WARN', '警告'), ('ERROR', '错误')], default='INFO', max_length=10)),
                ('category', models.CharField(choices=[('TASK', '任务'), ('STEP', '步骤'), ('ACTION', '动作'), ('ASSERTION', '断言'), ('ARTIFACT', '工件'), ('SYSTEM', '系统')], default='TASK', max_length=20)),
                ('message', models.CharField(blank=True, max_length=300)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('step_name', models.CharField(blank=True, max_length=200)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='api.uitask')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='UiArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('SCREENSHOT', '截图'), ('TRACE', 'Trace')], max_length=20)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('path', models.CharField(max_length=800)),
                ('url', models.CharField(blank=True, max_length=800)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.uistepresult')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='api.uitask')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='UiPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('url', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('enabled', models.BooleanField(default=True)),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ui_pages', to='api.module')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ui_pages', to='api.project')),
            ],
            options={
                'ordering': ['-id'],
                'unique_together': {('project', 'name')},
            },
        ),
        migrations.CreateModel(
            name='UiDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('schema', models.JSONField(blank=True, default=dict)),
                ('enabled', models.BooleanField(default=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ui_datasets', to='api.project')),
            ],
            options={
                'ordering': ['-id'],
                'unique_together': {('project', 'name')},
            },
        ),
        migrations.CreateModel(
            name='UiDatasetRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_key', models.CharField(blank=True, max_length=200)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('enabled', models.BooleanField(default=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='api.uidataset')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='UiElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('locator', models.JSONField(blank=True, default=dict)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('enabled', models.BooleanField(default=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='api.uipage')),
            ],
            options={
                'ordering': ['id'],
                'unique_together': {('page', 'name')},
            },
        ),
        migrations.CreateModel(
            name='UiPageMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('enabled', models.BooleanField(default=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='methods', to='api.uipage')),
            ],
            options={
                'ordering': ['id'],
                'unique_together': {('page', 'name')},
            },
        ),
        migrations.CreateModel(
            name='UiMethodStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('GOTO', '打开页面'), ('CLICK', '点击'), ('FILL', '输入'), ('PRESS', '按键'), ('WAIT', '等待'), ('ASSERT', '断言')], default='CLICK', max_length=20)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('assertions', models.JSONField(blank=True, default=dict)),
                ('enabled', models.BooleanField(default=True)),
                ('element', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.uielement')),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='api.uipagemethod')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='UiScenarioStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('type', models.CharField(choices=[('CALL_METHOD', '调用页面方法')], default='CALL_METHOD', max_length=20)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('enabled', models.BooleanField(default=True)),
                ('method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.uipagemethod')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenario_steps', to='api.uiscenario')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='UiRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mode', models.CharField(choices=[('HEADLESS', '无头'), ('HEADED', '有头')], default='HEADLESS', max_length=10)),
                ('total', models.PositiveIntegerField(default=0)),
                ('passed', models.PositiveIntegerField(default=0)),
                ('failed', models.PositiveIntegerField(default=0)),
                ('skipped', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='api.uidataset')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='api.uiscenario')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='uitask',
            name='dataset_row',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.uidatasetrow'),
        ),
        migrations.AddField(
            model_name='uitask',
            name='run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='api.uirun'),
        ),
    ]
